include "application"

mongo.uri = "mongodb://127.0.0.1:27017/lichess?appName=lila-ws"
study.mongo.uri = ${mongo.uri}
yolo.mongo.uri = ${mongo.uri}
redis.uri = "redis://127.0.0.1"

csrf.origin = "http://"${LIXIANGQI_DOMAIN}
csrf.extraOrigins = [
  "http://localhost:9663",
  "http://127.0.0.1:9663"
]
